#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]
//! EP-004: the repository, not only its Rust files, is part of the scan.
//!
//! Three rules read what git tracks: a tracked file whose name marks it as
//! secret-bearing, a source literal shaped like a real credential, and a
//! Cargo target directory git does not ignore. Every workspace here is built
//! and committed at test time inside a temporary git repository, so no
//! leak-shaped file is ever committed to this repository, and each test scans
//! through the same `inspect` a user runs. Key-shaped values are assembled at
//! runtime so no source file of this repository carries one.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::AtomicUsize;

use rust_doctor::{InspectRequest, RuleLevel, RuleOverride, Status, inspect};
use serde_json::Value;

mod support;

const SECRET_FILE: &str = "rust_doctor::repo::tracked_secret_file";
const CREDENTIAL: &str = "rust_doctor::repo::hardcoded_credential";
const BUILD_OUTPUT: &str = "rust_doctor::repo::unignored_build_output";

static NEXT_WORKSPACE: AtomicUsize = AtomicUsize::new(0);

fn workspace(scope: &str) -> PathBuf {
    let root = support::temporary_target(scope, &NEXT_WORKSPACE);
    if root.exists() {
        fs::remove_dir_all(&root).unwrap();
    }
    fs::create_dir_all(root.join("src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"repo-hygiene-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 4\n\n\
         [[package]]\n\
         name = \"repo-hygiene-fixture\"\n\
         version = \"0.1.0\"\n",
    )
    .unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() -> u32 {\n    2\n}\n").unwrap();
    root
}

fn git(root: &Path, arguments: &[&str]) {
    let output = Command::new("git")
        .args(arguments)
        .current_dir(root)
        .output()
        .expect("git should start");
    assert!(
        output.status.success(),
        "git {arguments:?}: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn commit_all(root: &Path) {
    git(root, &["init", "--quiet"]);
    git(root, &["config", "user.name", "Rust Doctor"]);
    git(
        root,
        &["config", "user.email", "rust-doctor@example.invalid"],
    );
    git(root, &["add", "-A"]);
    git(root, &["commit", "--quiet", "-m", "base"]);
}

fn report(root: &Path) -> Value {
    let report = inspect(InspectRequest::new(root));
    assert_eq!(report.status, Status::Complete, "{:?}", report.errors);
    serde_json::to_value(&report).expect("a valid report should serialize")
}

fn diagnostics_of<'a>(report: &'a Value, code: &str) -> Vec<&'a Value> {
    report["diagnostics"]
        .as_array()
        .expect("diagnostics should be an array")
        .iter()
        .filter(|diagnostic| diagnostic["code"] == code)
        .collect()
}

/// A deliberately fake AWS access key id: the documented example value from
/// the AWS credentials guide, which has never been a live credential.
fn fake_aws_key() -> String {
    format!("AKIA{}", "IOSFODNN7EXAMPLE")
}

/// US-012: tracked files whose names mark them as secret-bearing are each
/// reported at their path, with no span, without quoting a byte of their
/// contents, and the P1 security tier caps the overall score at 65.
#[test]
fn a_tracked_secret_file_is_reported_and_caps_the_security_dimension() {
    let root = workspace("repo-hygiene-secret");
    fs::write(root.join(".gitignore"), "/target\n").unwrap();
    fs::write(root.join(".env"), "EXAMPLE_ONLY=not-a-real-secret\n").unwrap();
    fs::write(root.join("deploy.key"), "placeholder, not a real key\n").unwrap();
    fs::write(root.join("credentials.json"), "{\"note\": \"placeholder\"}\n").unwrap();
    commit_all(&root);

    let report = report(&root);
    let observed = diagnostics_of(&report, SECRET_FILE);
    let mut paths: Vec<&str> = observed
        .iter()
        .filter_map(|finding| finding["path"].as_str())
        .collect();
    paths.sort_unstable();
    assert_eq!(paths, [".env", "credentials.json", "deploy.key"], "{report}");
    for finding in &observed {
        assert!(finding["span"].is_null(), "{finding}");
        assert!(finding["context"].is_null(), "{finding}");
    }
    // The report names the paths and never their contents.
    let serialized = report.to_string();
    assert!(!serialized.contains("EXAMPLE_ONLY"));
    assert!(!serialized.contains("not-a-real-secret"));
    // P1 security: the dimension is capped at 50 and the overall score at 65.
    assert!(report["audit"]["score"]["value"].as_u64().unwrap() <= 65, "{report}");
}

/// US-011: the published path is escaped exactly once, so a consumer that
/// decodes it recovers the tracked file rather than a name that never existed.
#[test]
fn a_path_needing_an_escape_is_published_escaped_once() {
    let root = workspace("repo-hygiene-escape");
    fs::write(root.join(".gitignore"), "/target\n").unwrap();
    fs::write(root.join("server%1.pem"), "placeholder, not a certificate\n").unwrap();
    commit_all(&root);

    let report = report(&root);
    let observed = diagnostics_of(&report, SECRET_FILE);
    assert_eq!(observed.len(), 1, "{report}");
    assert_eq!(observed[0]["path"], "server%251.pem", "{}", observed[0]);
}

/// US-012: the example variants of `.env` and certificates under test
/// material directories are the fixture, not the leak.
#[test]
fn example_variants_and_test_material_certificates_stay_silent() {
    let root = workspace("repo-hygiene-example");
    fs::write(root.join(".gitignore"), "/target\n").unwrap();
    fs::write(root.join(".env.example"), "EXAMPLE=\n").unwrap();
    fs::write(root.join(".env.template"), "TEMPLATE=\n").unwrap();
    fs::write(root.join(".env.sample"), "SAMPLE=\n").unwrap();
    fs::create_dir_all(root.join("tests/fixtures")).unwrap();
    fs::write(
        root.join("tests/fixtures/server.pem"),
        "not a certificate\n",
    )
    .unwrap();
    fs::create_dir_all(root.join("testdata")).unwrap();
    fs::write(root.join("testdata/ca.pem"), "not a certificate\n").unwrap();
    commit_all(&root);

    let report = report(&root);
    assert!(diagnostics_of(&report, SECRET_FILE).is_empty(), "{report}");
    assert!(diagnostics_of(&report, CREDENTIAL).is_empty(), "{report}");
}

/// US-012 and US-014: the pass reads what git tracks, so a `.env` present on
/// disk but never added, even one carrying a key-shaped value, is invisible
/// to both rules, because the file was correctly kept out of the repository.
#[test]
fn an_untracked_env_stays_out_of_the_report() {
    let root = workspace("repo-hygiene-untracked");
    fs::write(root.join(".gitignore"), "/target\n").unwrap();
    commit_all(&root);
    fs::write(root.join(".env"), format!("KEY={}\n", fake_aws_key())).unwrap();

    let report = report(&root);
    assert!(diagnostics_of(&report, SECRET_FILE).is_empty(), "{report}");
    assert!(diagnostics_of(&report, CREDENTIAL).is_empty(), "{report}");
}

/// US-011: a workspace outside version control is an observed fact, not an
/// error. The pass returns nothing, records nothing, and the scan stays
/// complete and authoritative.
#[test]
fn a_workspace_outside_git_produces_no_finding_and_stays_authoritative() {
    let root = std::env::temp_dir().join(format!(
        "rust-doctor-repo-hygiene-nongit-{}",
        std::process::id()
    ));
    if root.exists() {
        fs::remove_dir_all(&root).unwrap();
    }
    fs::create_dir_all(root.join("src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"repo-hygiene-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n\
         # It is not intended for manual editing.\n\
         version = 4\n\n\
         [[package]]\n\
         name = \"repo-hygiene-fixture\"\n\
         version = \"0.1.0\"\n",
    )
    .unwrap();
    fs::write(root.join("src/lib.rs"), "pub fn fixture() -> u32 {\n    2\n}\n").unwrap();
    fs::write(root.join(".env"), "EXAMPLE_ONLY=untracked\n").unwrap();

    let report = report(&root);
    for code in [SECRET_FILE, CREDENTIAL, BUILD_OUTPUT] {
        assert!(diagnostics_of(&report, code).is_empty(), "{code}: {report}");
    }
    assert!(
        report["errors"]
            .as_array()
            .unwrap()
            .iter()
            .all(|error| error["stage"] != "repo"),
        "{report}"
    );
    assert_eq!(report["complete"], true, "{report}");
    assert_eq!(report["audit"]["score"]["authoritative"], true, "{report}");

    fs::remove_dir_all(&root).unwrap();
}

/// US-013: with no `.gitignore` at all the target directory is not ignored
/// and the rule reports it once; adding the ignore line silences the same
/// workspace on the next scan.
#[test]
fn a_missing_gitignore_reports_the_unignored_target_directory() {
    let root = workspace("repo-hygiene-unignored");
    commit_all(&root);

    let before = report(&root);
    let observed = diagnostics_of(&before, BUILD_OUTPUT);
    assert_eq!(observed.len(), 1, "{before}");
    assert_eq!(observed[0]["path"], "target");
    assert!(observed[0]["span"].is_null(), "{}", observed[0]);

    fs::write(root.join(".gitignore"), "/target\n").unwrap();
    let after = report(&root);
    assert!(diagnostics_of(&after, BUILD_OUTPUT).is_empty(), "{after}");
}

/// US-013: the question is whether builds stay out, not which file says so.
/// `target` ignored through `.git/info/exclude` rather than the committed
/// `.gitignore` is silence.
#[test]
fn target_ignored_through_the_repository_exclude_file_stays_silent() {
    let root = workspace("repo-hygiene-exclude");
    commit_all(&root);
    fs::write(root.join(".git/info/exclude"), "target/\n").unwrap();

    let report = report(&root);
    assert!(diagnostics_of(&report, BUILD_OUTPUT).is_empty(), "{report}");
}

/// US-013: a custom `target-dir` in `.cargo/config.toml` is the directory
/// checked: the stock `target` being ignored does not answer for it.
#[test]
fn a_custom_target_dir_is_the_directory_checked() {
    let root = workspace("repo-hygiene-custom-target");
    fs::create_dir_all(root.join(".cargo")).unwrap();
    fs::write(
        root.join(".cargo/config.toml"),
        "[build]\ntarget-dir = \"build-out\"\n",
    )
    .unwrap();
    fs::write(root.join(".gitignore"), "/target\n").unwrap();
    commit_all(&root);

    let report = report(&root);
    let observed = diagnostics_of(&report, BUILD_OUTPUT);
    assert_eq!(observed.len(), 1, "{report}");
    assert_eq!(observed[0]["path"], "build-out");
}

/// US-014: a committed literal matching a closed credential prefix is
/// reported at its line with the pattern name, and the matched value never
/// appears anywhere in the report.
#[test]
fn hardcoded_credentials_are_reported_by_pattern_name_without_the_value() {
    let root = workspace("repo-hygiene-credential");
    fs::write(root.join(".gitignore"), "/target\n").unwrap();
    let key = fake_aws_key();
    fs::write(
        root.join("src/lib.rs"),
        format!("pub fn fixture() -> &'static str {{\n    \"{key}\"\n}}\n"),
    )
    .unwrap();
    commit_all(&root);

    let report = report(&root);
    let observed = diagnostics_of(&report, CREDENTIAL);
    assert_eq!(observed.len(), 1, "{report}");
    let finding = observed[0];
    assert_eq!(finding["path"], "src/lib.rs");
    assert_eq!(finding["span"]["line_start"], 2, "{finding}");
    assert!(
        finding["message"]
            .as_str()
            .is_some_and(|message| message.contains("AWS access key id")),
        "{finding}"
    );
    assert!(finding["context"].is_null(), "{finding}");
    // FR-12: neither the terminal nor the JSON carries the matched value.
    assert!(!report.to_string().contains(&key));
    // P1 security: the finding weighs and caps the overall score at 65.
    assert!(report["audit"]["score"]["value"].as_u64().unwrap() <= 65, "{report}");
}

/// US-014: the same literal under a test path is published with the
/// non-production context marker and stops weighing: no cap applies.
#[test]
fn a_credential_in_test_material_carries_the_context_marker_and_does_not_weigh() {
    let root = workspace("repo-hygiene-test-context");
    fs::write(root.join(".gitignore"), "/target\n").unwrap();
    fs::create_dir_all(root.join("tests")).unwrap();
    let token = format!("xoxb-{}", "1234567890ab");
    fs::write(
        root.join("tests/support_data.rs"),
        format!("pub const FAKE: &str = \"{token}\";\n"),
    )
    .unwrap();
    commit_all(&root);

    let report = report(&root);
    let observed = diagnostics_of(&report, CREDENTIAL);
    assert_eq!(observed.len(), 1, "{report}");
    assert_eq!(observed[0]["context"], "tests", "{}", observed[0]);
    assert!(report["audit"]["score"]["applied_ceiling"].is_null(), "{report}");
    assert!(report["audit"]["score"]["value"].as_u64().unwrap() > 65, "{report}");
}

/// FR-15: all three rules stay switchable off through the same override
/// surface as every other rule.
#[test]
fn the_three_rules_are_switchable_off() {
    let root = workspace("repo-hygiene-switch-off");
    fs::write(root.join(".env"), "EXAMPLE_ONLY=placeholder\n").unwrap();
    let key = fake_aws_key();
    fs::write(
        root.join("src/lib.rs"),
        format!("pub fn fixture() -> &'static str {{\n    \"{key}\"\n}}\n"),
    )
    .unwrap();
    commit_all(&root);

    let mut request = InspectRequest::new(&root);
    for code in [SECRET_FILE, CREDENTIAL, BUILD_OUTPUT] {
        request = request.with_rule_override(RuleOverride::new(code, RuleLevel::Off));
    }
    let report = inspect(request);
    assert_eq!(report.status, Status::Complete, "{:?}", report.errors);
    let report = serde_json::to_value(&report).expect("a valid report should serialize");
    for code in [SECRET_FILE, CREDENTIAL, BUILD_OUTPUT] {
        assert!(
            diagnostics_of(&report, code).is_empty(),
            "{code} still fired switched off"
        );
    }
}
