// @generated by a code generator. DO NOT EDIT.
//
// Unreached like its neighbour, and silent: what a generator writes is nobody's
// writing, so no structural detector reads it.

pub fn produced() -> u8 {
    2
}
